### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ElizabethHanson1999** [arsium/BypassUAC#1]
Hi 
Thankyou for sharing 

I executed the BypassUAC.exe from a shell. but the elevated cmd console open locally. is ther any way to redirecting output to remote session ?

**Comment by arsium** [comment]
> Hi 
> Thankyou for sharing 
> 
> I executed the BypassUAC.exe from a shell. but the elevated cmd console open locally. is ther any way to redirecting output to remote session ? 

I think you could redirect it only if you have same right (cmd opened as admin could not be redirected to a non admin process) and maybe parent process could even not same rights

**Comment by ElizabethHanson1999** [comment]
Thank you for reply ... 
If i had an administrator cmd, it dosent need to bypass uac. I have an admin ( not administrator ) shell so i need to bypass uac to execute some elevated commands ... if it's not possible ... anyway...  what about  a way to send an elevated command to bypassuac.exe to run it in background locally atleast ? is it possible in this code ?

**Comment by arsium** [comment]
> Thank you for reply ... 
> If i had an administrator cmd, it dosent need to bypass uac. I have an admin ( not administrator ) shell so i need to bypass uac to execute some elevated commands ... if it's not possible ... anyway...  what about  a way to send an elevated command to bypassuac.exe to run it in background locally atleast ? is it possible in this code ? 

Did you read the code ? ShellExec is a function whose one of args is a command I just set it to null here
So yes it is possible to do it
